### ISSUE TITLE
Error with code

### ISSUE THREAD

**Issue by IamC8** [inAudible-NG/audible-activator#1]
Hi, I get the following error:

Traceback (most recent call last):
  File "./audible-activator.py", line 136, in <module>
    fetch_activation_bytes(sys.argv[1], sys.argv[2])
  File "./audible-activator.py", line 72, in fetch_activation_bytes
    s.cookies.set(cookie['name'], cookie['value'])
AttributeError: 'dict' object has no attribute 'set'

Please advice.

Ok, strange thing. Second time around it worked fine and I got the code.
Thanks!

**Comment by inAudible-NG** [comment]
It is great that you got it working :)
