### ISSUE TITLE
Unix: chromedriver is only searched for in current dir, not on PATH.

### ISSUE THREAD

**Issue by felixbecker2** [inAudible-NG/audible-activator#12]
On UNIX-systems, `chromedriver` is searched for only in the working dir. It should be searched for in the `$PATH`.

You need to change (line 54 at the time of writing this)

OLD:
```python
        chromedriver_path = "./chromedriver"
```

to

SHOULD BE:
```python
        chromedriver_path = "chromedriver"
```

**Comment by inAudible-NG** [comment]
I prefer keeping "chromedriver" file in the current folder. The instructions in the "Quick Setup" section also clearly mention that "chromedriver" file should be in current (repository) folder.
