### ISSUE TITLE
Player ID returned by script is not hex, but hex is expected.

### ISSUE THREAD

**Issue by felixbecker2** [inAudible-NG/audible-activator#13]
The player ID returned by the script is for me not hex, and when I provide it back to the script it complains that non-hexadecimal digits are found. So, could be useful to either convert the player ID to hex and output that as well, or accept non-hex player ID:

```
$ ./audible-activator.py -d -l de
Username: [entered via keyboard -- censored]
Password: [entered via keyboard -- not shown]
[*] Player ID is 2j[censored]/Y[censored]=
[chromium window shows up, things are getting done, and the activation bytes are returned]
```

Player ID seems to may contain all characters from the set `[a-zA-U0-9]`, and some more (I have `/` and `=`).

So, when I then try to start the script with that player ID, it complains:

```
$ ./audible-activator.py -d -l de -p '2j[censored]/Y[censored]='
Username: [entered via keyboard -- censored]
Password: [entered via keyboard -- not shown]
Traceback (most recent call last):
  File "./audible-activator.py", line 134, in <module>
    fetch_activation_bytes(username, password, options)
  File "./audible-activator.py", line 39, in fetch_activation_bytes
    player_id = base64.encodestring(binascii.unhexlify(options.player_id)).rstrip()
TypeError: Non-hexadecimal digit found
```

**Comment by inAudible-NG** [comment]
This option is not meant to be used by end-users (it is for internal debugging purposes). The "Player ID" is currently hardcoded in the script.

If you still want to use it then you can base64 decode and hex encode the '2j[censored]/Y[censored]=' string before feeding it to the `audible-activator.py` script.
