### ISSUE TITLE
script doesn't support logging-in to audible with amazon.com accounts

### ISSUE THREAD

**Issue by vorophobe** [inAudible-NG/audible-activator#14]
I managed to get the script working, but I had to disable the login part of your code as I use an amazon.com account to login to audible (which it wouldn't accept without going through a different login screen)

Thank you for this tool btw, I'm very happy!

**Comment by inAudible-NG** [comment]
If you use your amazon.com email address as the username, then the script should automatically show the amazon.com login screen (and not the audible username login screen). I don't know what went wrong. You can also use the "./audible-activator.py -d" command to troubleshoot login problems.

This said, I am happy that you were able to solve this problem. Thanks!
