### ISSUE TITLE
Linux selenium installation problems

### ISSUE THREAD

**Issue by dessalines** [inAudible-NG/audible-activator#17]
I had some difficulty installing this on linux, it was unable to find the chromedriver, even after using `sudo apt install chromium-chromedriver`.

Eventually the only way I could get it to work, was to download the 32-bit  `chromedriver` manually from [here](http://chromedriver.storage.googleapis.com/index.html), and then change the code to do:

```python
driver = webdriver.Chrome('/home/X/Downloads/chromedriver')
```

**Comment by inAudible-NG** [comment]
The documentation clearly says "Download and extract the correct ChromeDriver zip file from here to this folder". It seems you missed reading the documentation clearly.
