### ISSUE TITLE
Thanks! Couple documentation suggestions

### ISSUE THREAD

**Issue by ryan-williams** [inAudible-NG/audible-activator#2]
This is so great, thank you!

A couple of snags I hit:
* Python 2 required, seemingly!
* The [ChromeDriver list](http://chromedriver.storage.googleapis.com/index.html?path=2.19/) doesn't have a 64-bit OSX option; I used the 32bit one and it seemed to work though. Also had to move the existing `chromedriver` in this repo out of the way first.

**Comment by inAudible-NG** [comment]
@ryan-williams thanks for the feedback, I have fixed the documentation now.
