### ISSUE TITLE
Activation failed after correct login

### ISSUE THREAD

**Issue by dtu-compute** [inAudible-NG/audible-activator#23]
It opens the Chrome window and then a login with a captcha which fill out and it logs in, but I get the below error.

```
./audible-activator.py -d --username="xxx" --password="xxx"
[*] Player ID is 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
[!] Running in DEBUG mode. You will need to login in a semi-automatic way, wait for the login screen to show up ;)
(audible_error=Internal service error has occured while processing the request, please contact service admin.)


Activation failed! ;(
```

**Comment by dtu-compute** [comment]
If I try to navigate to My Books I get
```
Traceback (most recent call last):
  File "./audible-activator.py", line 148, in <module>
    fetch_activation_bytes(username, password, options)
  File "./audible-activator.py", line 91, in fetch_activation_bytes
    + 'customer_token=' + data["playerToken"] + "&action=de-register"
KeyError: 'playerToken'
```

**Comment by inAudible-NG** [comment]
After you have logged in with a captcha, do not click or navigate anywhere in the browser window.

Have you read https://github.com/inAudible-NG/audible-activator/blob/master/README.md carefully? It says,

If you see an error message like "audible_error=Internal service error has occured while processing the request, please contact service admin" during the activation process, then contact Audible customer care and they will clear up your activation slots (there are 8 such slots).

The alternate solution is to use https://github.com/inAudible-NG/tables to recover "activation_bytes".

**Comment by dtu-compute** [comment]
Sorry, I missed that part.

I now contacted support about getting the activation slots reset and they said:

> You only have one activation at the moment, and it is for your android, you do not need your activation reset.

They told me also that there is no limit on the number of devices I can use.

What can you extract from this?

**Comment by dtu-compute** [comment]
Now tried `rcrack` and it worked perfectly.

**Comment by inAudible-NG** [comment]
I love the `rcrack` method. It works without a fuss.
