### ISSUE TITLE
Assumes "chromedriver" is at "./chromedriver"

### ISSUE THREAD

**Issue by robertseaton** [inAudible-NG/audible-activator#24]
Hi, 

Mostly documenting this here in case anyone runs into the same problem -- I see now based on the quick start info in your readme that it's assumed that the chromedriver binary is in the same folder as `audible-activator.py`. 

Anyway, to any googlers, if you get this error message:

    Traceback (most recent call last):
      File "audible-activator.py", line 148, in <module>
        fetch_activation_bytes(username, password, options)
      File "audible-activator.py", line 57, in fetch_activation_bytes
        executable_path=chromedriver_path)
      File "/usr/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
        self.service.start()
      File "/usr/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 81, in start
        os.path.basename(self.path), self.start_error_message)
    selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be     in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

    Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f04c6f59d10>> ignored

and you have `chromedriver` in your path, you need to change `audible-activator.py` from

    if sys.platform == 'win32':
            chromedriver_path = "chromedriver.exe"
    else:
            chromedriver_path = "./chromedriver"
to

    if sys.platform == 'win32':
            chromedriver_path = "chromedriver.exe"
    else:
            chromedriver_path = "chromedriver"

**Comment by hhiru** [comment]
I have a similar problem but I keep getting the error.. I have this PATH in my system variables:

    C:\Users\hiru\audible-activator-master\chromedriver.exe

and I edited the `audible-activator.py` file like you did but still get the error :/

**Comment by inAudible-NG** [comment]
@robertseaton Thanks for your report.

@hhiru You will have to debug this problem on your own (seems like a local configuration problem). Good luck.
