### ISSUE TITLE
Not getting the correct code

### ISSUE THREAD

**Issue by jlieb10** [inAudible-NG/audible-activator#28]
Install and running go smoothly but the code returned does not work with activation bytes. I've double checked my copy and pasting, and file name downloaded. The code returned is also lowercase which, when searching for issues with this project, I haven't seen. I tried the code returned, the code returned uppercased, the code with bytes reversed, and the code with bytes reversed uppercase but none of it works. I'm trying to work with your tables repo now, but am an OSX user so dealing with wine etc is a bit of a nightmare.

**Comment by jlieb10** [comment]
After installing the necessary dependencies to use the tables repo on a mac, I got a different set of activation bytes, but those worked fine. not sure what accounts for the discrepancy.

**Comment by inAudible-NG** [comment]
This project has too many moving parts, things which can go wrong for unknown reasons. In comparison, `https://github.com/inAudible-NG/tables` is near perfect ;)

Thanks for your report.

**Comment by inAudible-NG** [comment]
If you would like to debug and solve this problem, send me a copy of `activation.blob` (saved to the disk by this project) and the SHA-1 checksum extracted from the .aax file using `ffprobe` utility (as done in the `tables` repository).
