### ISSUE TITLE
How to reset activations?

### ISSUE THREAD

**Issue by sfgasdfsafggfgg** [inAudible-NG/audible-activator#5]
I get the error message "audible_error=Internal service error has occured while processing the request, please contact service admin", so I may need to clear activations, but what do I ask customer service? I don't want them to think I'm removing the DRM as that's not allowed.

**Comment by inAudible-NG** [comment]
@sfgasdfsafggfgg How did you get it working again? It would be nice to have this fix documented, thanks!

**Comment by inAudible-NG** [comment]
In worst case, you can use the https://github.com/inAudible-NG/tables project to retrieve your own activation key from your own files.
