### ISSUE TITLE
audible.de does not work

### ISSUE THREAD

**Issue by papamoose** [inAudible-NG/audible-activator#7]
Can someone fix this so it works with audible.de as well?
I can run the script and it will return a byte code but it will not decrypt my audible files from audible.de. Presumably, this is because the code is for any book downloaded from audible.com.

**Comment by inAudible-NG** [comment]
I cannot reproduce this on my end. Please post more details, output, and AAX samples.

The program is pretty short, and easy to debug. I cannot produce end-user support but I would be very happy to accept patches.

If all else fails, use https://github.com/inAudible-NG/tables to recover your "activation_bytes".

**Comment by inAudible-NG** [comment]
Closing this bug since the reporter is "MIA", and I don't have to way to confirm this bug.

**Comment by jasontrublu** [comment]
I have the same problem. I guess the login URL is different for audible.de

**Comment by jasontrublu** [comment]
fixed in my fork. But needs proper integration with a switch or something. Don't know anything about python, so I'm not the most qualified to do that

**Comment by jasontrublu** [comment]
I created #8 to fix this problem
