### ISSUE TITLE
Not working with 2 factor auth enabled.

### ISSUE THREAD

**Issue by stp-ip** [inAudible-NG/audible-activator#9]
It reloads the page before one can enter the 2 factor.

**Comment by inAudible-NG** [comment]
@stp-ip 

Try running the program as `./audible-activator.py -d` and then handle the authentication part manually yourself in the browser. Please report back if this works.

**Comment by stp-ip** [comment]
Thanks. Will look into it, when I get back into the office. End of April.

**Comment by inAudible-NG** [comment]
The original reporter seems to be gone, hence closing this bug.

**Comment by stp-ip** [comment]
Sorry. Yeah it worked. Thanks
